-- Migration: create rewards and purchases tables

CREATE TABLE IF NOT EXISTS `rewards` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `handle` VARCHAR(64) NOT NULL UNIQUE,
  `title` TEXT NOT NULL,
  `description` TEXT,
  `priceCredits` INT NOT NULL DEFAULT 0,
  `effect` TEXT,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `purchases` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `userId` INT NOT NULL,
  `rewardId` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `metadata` TEXT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`rewardId`) REFERENCES `rewards`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
